### ISSUE TITLE
QLEVER_BIN_DIR not picked up / awkward usage

### ISSUE THREAD

**Issue by WolfgangFahl** [ad-freiburg/qlever-control#2]
I am trying to follow the instructions of the README and did the steps as outlined in https://wiki.bitplan.com/index.php/WikiData_Import_2022-05-21

After modifying the Qleverfile for the olympics example:
```bash
rcsdiff ./Qleverfile 
===================================================================
RCS file: ./RCS/Qleverfile,v
retrieving revision 1.1
diff -r1.1 ./Qleverfile
6,7c6,7
< DB               = must_specify
< RDF_FILES        = 
---
> DB               = olympics 
> RDF_FILES        = olympics.nt
21c21
< QLEVER_BIN_DIR          = /local/data/qlever/qlever-code/build
---
> QLEVER_BIN_DIR          = /hd/seel/qlever/qlever-code/build/ 
```
I ran:
```bash
qlever index

This is the "qlever" script, call without argument for help

Executing "index":

cat olympics.nt | IndexBuilderMain -F ttl -K olympics -f - -i olympics -s olympics.settings.json | tee olympics.index-log.txt

/hd/seel/qlever/qlever-control/qlever: line 116: IndexBuilderMain: command not found

```
which seems to expect IndexBuilderMain in the PATH instead of picking up the QLEVER_BIN_DIR setting. What is QLEVER_BIN_DIR for if not for avoding this?

**Comment by WolfgangFahl** [comment]
```bash
cat olympics.nt | /hd/seel/qlever/qlever-code/build/IndexBuilderMain -F ttl -K olympics -f - -i olympics -s olympics.settings.json | tee olympics.index-log.txt
```
is the workaround for me

**Comment by Qup42** [comment]
> which seems to expect IndexBuilderMain in the PATH instead of picking up the QLEVER_BIN_DIR setting. What is QLEVER_BIN_DIR for if not for avoding this?

`QLEVER_BIN_DIR` (and also `QLEVER_CMD_DIR`) should be added to the path when running `. qlever`. After that it should work as expected. At least in theory.
https://github.com/ad-freiburg/qlever-control/blob/466eb926ffa0b1c853a5ecb5c53d5519adfc2727/qlever#L442-L448

**Comment by Qup42** [comment]
This seems to not work because the custom values from the `Qleverfile` are only loaded after the path has been set. Because the custom values are not loaded early enough the default values (`/local/data/qlever/qlever-code/build` for `QLEVER_BIN_DIR`) will always be used when updating the path. Thus your custom `QLEVER_BIN_DIR` is not added to the path.

------

The default value for `QLEVER_BIN_DIR` is set in Line 400. The path is updated in lines 442 to 448. The `Qleverfile` is only loaded later in Line 700.
https://github.com/ad-freiburg/qlever-control/blob/466eb926ffa0b1c853a5ecb5c53d5519adfc2727/qlever#L400
https://github.com/ad-freiburg/qlever-control/blob/466eb926ffa0b1c853a5ecb5c53d5519adfc2727/qlever#L442-L448
https://github.com/ad-freiburg/qlever-control/blob/466eb926ffa0b1c853a5ecb5c53d5519adfc2727/qlever#L696-L700
